- .gitignore
- .travis.yaml
- CMakeLists.txt
- EDM4HEPVersion.h
- cmake/EDM4HEP.pc.in
- cmake/EDM4HEPCPack.cmake
- cmake/EDM4HEPConfig.cmake.in
- cmake/EDM4HEPCreateConfig.cmake
- cmake/EDM4HEPDoxygen.cmake
- cmake/EDM4HEPUninstall.cmake
- cmake/EDM4HEP_uninstall.cmake.in
- edm4hep.yaml
- edm4hep/CMakeLists.txt
- init.sh
Added a MCParticle class just to test the technicalities - running the class generator, compiling the library, creating the dictionaries, etc. The config is pulled from HSF/tools, HEP-FCC/fcc-edm and AIDASoft/podio, and just a starting point.
It seems I still have trouble getting the CI to mount cvmfs, working on it.
> Build infrastructure - CMake and CI

- CMakeLists.txt
- edm4hep.yaml
- fix component names according discussion at CERN: [https://codimd.web.cern.ch/NtM0GlENRFG5Wc_bAn_sxA?both#](https://codimd.web.cern.ch/NtM0GlENRFG5Wc_bAn_sxA?both#)
- add some extraCode for convenient methods to MCParticle 
- to be discussed if we want these in this way 
- fix the install directories to observe `CMAKE_INSTALL_PREFIX`
- follow cmake updates in AIDASoft/podio#54
> Fix components

- CMakeLists.txt
- README.md
> Add Travis Build Status

- edm4hep.yaml
.. these are the SimTrackerHit and CalorimeterHit  as defined in plcio/LCIO, except with
the two int cellIDs replaced with on 'unsgined long long' as suggested by @vvolkl.
(this PR replaces #6).
> [WIP] add SimTrackerHit and CalorimeterHit proposals

- .github/ISSUE_TEMPLATE
- .github/PULL_REQUEST_TEMPLATE
- README.md
- doc/ReleaseNotes.md
- doc/contributing.md
- add some templates for pull requests and issues
- add contributing guidelines
> add templates, relnotes and contributing guidelines

- test/read_events.cc
- test/write_events.cc
- Replace tabs in test directory by spaces
> Whitespace Fixes

- .edm4hep-ci.d/compile_and_test_with_podio.sh
Should speed up the build until we have some nightlies
- Skip building podio tests in CI
> Skip building podio tests in CI

- edm4hep.yaml
- Add adapted plcio Calorimeter types  needed for a full working version
> Calorimeter Reco Types

- README.md
- doc/edm4hep_diagram.svg
- edm4hep.yaml
- add  diagram showing association between types
- improve whitespace in edm4hep.yaml
- update Readme
> Documentation and Readme Update

- CMakeLists.txt
- edm4hep/CMakeLists.txt
- test/CMakeLists.txt
- Cmake: remove directory properties, needs AIDASoft/podio#68
> CMake: cleanup, use PODIO_GENERATE_DICTIONARY

- .edm4hep-ci.d/compile_and_test.sh
- .edm4hep-ci.d/compile_and_test_with_podio.sh
- test/CMakeLists.txt
- Cmake: if BUILD_TESTING=OFF no tests are compiled
> trick track tests, and CI improvements

- CMakeLists.txt
- dataframe/CMakeLists.txt
- dataframe/edm4hepRDF.cc
- dataframe/edm4hepRDF.h
- dataframe/selection.xml
- init.sh
- test/CMakeLists.txt
- test/test_rdf.cc
- add library + dict with lambdas for use with rdataframe
> RDataFrame Helpers

- edm4hep/CMakeLists.txt
- plugins/DDG4EDM4hep/CMakeLists.txt
- Use PODIO_GENERATE_DATAMODEL, needs #aidasoft/podio#73, fixes #49 
> better generation of sources

- plugins/DDG4EDM4hep/edm4hep/Geant4Output2EDM4hep.cpp
- test/hepmc/edm4hep_testhepmc.cc
- Adapt to new naming of functions in podio
This PR just fixes all the remaining places in the tests and the plugins which are not yet covered by a previous [commit](https://github.com/key4hep/EDM4hep/commit/f3d997d6909dc2e4767191d3fab2da86a8941b85)
> Fix tests/plugin after podio #88

- plugins/DDG4EDM4hep/CMakeLists.txt
- plugins/DDG4EDM4hep/edm4hep/Geant4Output2EDM4hep.cpp
- finalize the EDM4hep output module for DDG4/ddsim
- add treatment of event parameter meta data
> Fix edm4hep output for DDG4

- plugins/delphes/CMakeLists.txt
- plugins/delphes/Delphes.cc
- plugins/delphes/Delphes.h
- plugins/delphes/DelphesEDM4HepConverter.cc
- plugins/delphes/DelphesEDM4HepConverter.h
- plugins/delphes/DelphesMain.h
- split eventstore functionality from edm4hep converter
> [Delphes]: split eventstore functionality from converter

- edm4hep.yaml
- Updated datamodel definition yaml file to work with new podio version
Fixes #71 
After the podio code generation refactoring (AIDASoft/podio#117) some changes to the datamodel definition are necessary. These changes also include the necessary changes for #71.
> Update datalayout to new podio version

- edm4hep.yaml
- Fix capitalization in edm4hep.yaml: pDG -> PDG
> Fix capitalization in edm4hep.yaml

- plugins/delphes/DelphesEDM4HepConverter.cc
- save the delphes particle status as edm4hep::MCparticle.GeneratorStatus
> [delphes] convert particle status

- plugins/delphes/examples/EDM4Hep2LCIO_example.py
- Add a python script to convert EDM4Hep to LCIO
- Currently just converting ReconstructedParticles and Tracks
> add EDM4Hep2LCIO_example

- CMakeLists.txt
- cmake/EDM4HEPBuild.cmake
- Add rpath setup and update compiler flags and linker setup
> Add rpath setup and update compiler flags and linker setup

- doc/edm4hep_diagram.svg
Fixes #109 
Also I used an inkscape filter on the text boxes so that the background will be correctly resized when the text is changed.
- Update relation diagram for docs
Preview:
> [doc] update diagram

- .gitignore
- test/CMakeLists.txt
- test/hepmc/edm4hep_testhepmc.cc
- switch to hepmc3 in tests
Fixes #60
> Switch to HepMC3 in tests

- .gitlab-ci.yml
- doc/edm4hep_diagram.svg
- Fix doxygen generation - update setup on gitlab
- Update version string in diagram
> Fix doxygen generation

- test/read_events.h
- test/write_events.h
Since the write_events and read_events test files only contained examples from four classes, I expanded them with two more.
- Expanded write_events and read_events test with two new classes
> Expand tests with more classes

- .clang-format
- .github/scripts/clang-format-hook
- .github/workflows/lcg_linux_with_podio.yml
- .github/workflows/pre-commit.yml
- .gitlab-ci.yml
- .pre-commit-config.yaml
- README.md
- cmake/EDM4HEP.pc.in
- cmake/EDM4HEPBuild.cmake
- dataframe/edm4hepRDF.cc
- dataframe/edm4hepRDF.h
- doc/contributing.md
- doc/edm4hep_stylesheet.css
- edm4hep.yaml
- test/CMakeLists.txt
- test/downstream-project-cmake-test/main.cxx
- test/hepmc/edm4hep_testhepmc.cc
- test/read_events.cc
- test/read_events.h
- test/read_events_sio.cc
- test/reco_particle_ref.cc
- test/test_rdf.cc
- test/utils/test_kinematics.cpp
- test/write_events.cc
- test/write_events.h
- test/write_events_sio.cc
- utils/include/edm4hep/utils/kinematics.h
- Add a `pre-commit` and a `clang-format` config file and run them in CI.
> Add pre-commit and clang-format configuration and fix all issues

- README.md
- Updated line links to datatypes/components/associations in the README
> Updated line links to datatypes/components/associations

- edm4hep.yaml
- Fix a typo in setDecayedInCalorimeter.
> Fix a typo in setDecayedInCalorimeter.

- edm4hep.yaml
- Document some units for edm4hep::Vector3f fields
> Document units for edm4hep::Vector3f fields

- test/read_events.cc
- test/read_events.h
- test/read_events_sio.cc
- test/write_events.cc
- test/write_events.h
- test/write_events_sio.cc
- Make the I/O tests use `podio::Frame` functionality
> Make I/O tests use podio::Frame capabilities

- test/hepmc/edm4hep_testhepmc.cc
- Make the HepMC example use Frame based I/O
> Make the HepMC test use Frame based I/O

- doc/edm4hep_diagram.svg
- Replace TPCHit with RawTimeSeries
- Update version to 0.9
- Add TrackerPulse
> Update schema diagram

- tools/CMakeLists.txt
- Respect CMAKE_INSTALL_BINDIR
> Respect CMAKE_INSTALL_BINDIR

- .gitlab-ci.yml
Makes this up-to-date again: https://edm4hep.web.cern.ch/index.html
> CI: fix doxygen deployment

- .gitlab-ci.yml
> Gitlab: install graphviz for doxygen graphs

- doc/edm4hep_diagram.svg
- Bump the version in the schema diagram to v0.10
> Bump the version on the schema diagram

- test/read_events.cc
- test/read_events.h
- test/write_events.cc
- test/write_events.h
- Fix a few compiler warnings, some of them introduced in 1.0 PRs
> Fix a few compiler warnings

- README.md
- Fix readme formatting and links to trackerhit
> Fix readme formatting and links to trackerhit

- README.md
- include/edm4hep/detail/CovMatrixCommon.ipp
- test/utils/test_PIDHandler.cpp
- utils/include/edm4hep/utils/ParticleIDUtils.h
- Fix datatypes table formatting. Fix typos
> Fix datatypes table formatting and typos

- doc/edm4hep_diagram.svg
- Update the schema diagram to reflect the changes from [#268](https://github.com/key4hep/EDM4hep/pull/268)
I split this into two PRs, because #302 shouldn't be too controversial, while removing the version might be a bit less clear
> Update the schema diagram to reflect the new ParticleID to ReconstructedParticle relation

- doc/edm4hep_diagram.svg
- Update the `Link` names in the diagram after #341 
> Update the names of the links in the diagram

- test/utils/test_kinematics.cpp
- tools/include/edm4hep2json.hxx
- utils/include/edm4hep/utils/ParticleIDUtils.h
- utils/include/edm4hep/utils/TrackUtils.h
- Remove a few unnecessary includes
> Remove a few unnecessary includes

- edm4hep.yaml
- Clarify the comment on the Cluster direction members
> Clarify the documentation of the Cluster direction members

- edm4hep.yaml
- Fix capitalization of `eDep`in yaml comments
> fix capitalization of `eDep` in comments

- CITATION.cff
- README.md
Add citation information to README.md and corresponding CITATION.cff file
Closes #407
> Add citation info for ICHEP2022 paper

- edm4hep.yaml
- Clarify the `phi` member of the `TrackState`
- Specify units (radians) for members describing angles
Proposal to fix https://github.com/key4hep/EDM4hep/issues/419
> Clarify track state phi

- README.md
- edm4hep.yaml
Deprecated since February 2024
- Remove the deprecated constructor, getters and setters
> Remove the deprecated constructor, getters and setters
