.edm4hep-ci.d/compile_and_test_with_podio.sh
.travis.yml
CMakeLists.txt

It's certainly better to take podio from some nightlies on cvmfs, but as a stopgap solution this builds podio on the fly in CI jobs, works well enough for now.
As @graeme-a-stewart remarked, the lhcb docker run script is a bit overkill, so I replaced it with a direct call to `docker run`. 
* Use an extended script for CI builds that compiles and install the HEAD of podio on the fly. 

Build podio dependency on the fly in CI builds

---

edm4hep.yaml

- Add plcio-like types and some associations needed for a first working version: TrackState, ObjectID, TrackerHit, TPCHit, Track, Vertex, ReconstructedParticle, MCRecoParticleAssociation, MCRecoTrackerAssociation, MCRecoCaloAssociation

All Remaining Types for a First Working Version

---

.edm4hep-ci.d/compile_and_test_with_podio.sh
test/CMakeLists.txt
test/edm4hep_tricktrack.cc

- Add an integration test using the TrickTrack seeding library
The `x()`, `y()`, `z()`, `rho()` getter methods may be to discuss - I can change that on the podio side as well though.

 Add tricktrack integration test

---

.edm4hep-ci.d/compile_and_test_with_podio.sh
.gitignore

Because the init script was sourced twice [here] (https://github.com/HSF/EDM4hep/blob/master/.edm4hep-ci.d/compile_and_test.sh#L2), the local CI builds of dependencies were not correctly picked up.
- build system bugfix: Ensure that the CI picks up local version of packages also present in LCG

Build System: Ensure that  CI picks up local version of packages also present in LCG

---

edm4hep.yaml

This is a smaller version of the plcio equivalent, as I'm assuming here that podio will be able to put  parameters like `detectorname` in the metadata tree. Also, removing std::string members means the PODness remains intact.
- Add EventHeader data type

Add EventHeader data type

---

.edm4hep-ci.d/compile_and_test.sh
.edm4hep-ci.d/compile_and_test_with_podio.sh
.travis.yml

The `after_success` step, which is supposed to publish the page, failed due to a wrong directory name.

Fix TravisCI Configuration for Doxygen Generation

---

edm4hep.yaml

As discussed in the meetings, the MC/Reco associations are missing a weight to express possible uncertainties.
- add weights to associations

Add weights to associations

---

test/CMakeLists.txt

- fix linking on Ubuntu
- use -Wl,--no-as-needed for linking edm4hepDict (if available)
- follows https://github.com/AIDASoft/podio/pull/91

use -Wl,--no-as-needed for linking edm4hepDict

---

edm4hep.yaml

Plural forms for the variable names make it easier to recognize they refer to a vector.
- Rename cluster vectormembers with a plural form

Rename cluster vectormembers in plural form

---

edm4hep.yaml

Since it doesn't mutate any of the internals it should be marked const
- mark MCParticle::getEnergy const to make it accessible in const context

Mark MCParticle::getEnergy const

---

edm4hep/CMakeLists.txt
test/CMakeLists.txt

Analogous to https://github.com/AIDASoft/podio/pull/99
- The rootmap file should point to the dictionary library, and not the base library
- Tests: Fill the LD_LIBRARY_PATH environment variable with the location of the rootmap file

Fix rootmap

---

plugins/DDG4EDM4hep/CMakeLists.txt

DD4hepINSTALL is more consistently used in DD4hep itself
- Change DD4hep environment variable in tests

Change DD4hep Env var used to find compact files.

---

edm4hep.yaml

- Add additional comment to `mass`, `energy` and `momentum` members of `ReconstructedParticle` description to clearly state that the 4-momentum state is not automatically kept consistent internally. Since there are too many different use-cases, a general solution that always works was deemed hard to achieve and it is, thus, the users responsibility to keep this state consistent if it is necessary.
It is still necessary to set the mass after the momentum has been set to get everything really consistent, but without a 4-vector type, I think that is hard to achieve.

Add more description concerning the internal 4-momentum state of ReconstructedParticle

---

.edm4hep-ci.d/compile_and_test.sh
.edm4hep-ci.d/compile_and_test_with_podio.sh
.travis.yml

Cleaned up some of the variables too, since we are not using exclusively the lcg setup scripts.
- CI Update: Add option to build PODIO on the fly, dev3
I'm also adding a  clang build with dev3 as well, for better coverage, but  only the build against the key4hep nightlies (gcc8) with the current podio master is required to pass.

CI Update: Add option to build PODIO on the fly, dev3

---

CMakeLists.txt

The current CPack configuration (from the HSF template) tries to guess the platform, but fails with an error on some platforms such as arch. In order not to have to patch anything, this is turned off by default.
- Add a cmake option for cpack

[cmake] option for cpack

---

plugins/delphes/CMakeLists.txt
plugins/delphes/DelphesEDM4HepConverter.cc
plugins/delphes/DelphesPythia8Reader.h
plugins/delphes/examples/higgs_recoil_plots.C

- fix delphes EDM4Hep plugin
- set energy for clusters and reco particles in DelphesEDM4HepConverter
- add example higgs_recoil_plots.C  (same as in delphes2lcio)
- minor fix for building DelphesPythia8 on MacOS
- make plugin compatible w/ Pythia8.3

Fix delphes EDM4Hep plugin

---

plugins/delphes/DelphesEDM4HepConverter.cc
plugins/delphes/README.md
plugins/delphes/edm4hep_output_config.tcl

Otherwise we would select on the delphes class, which could lead to the
problem that we could accidentally select more branches than we had
anticipated. There would be not possibility to only select a subset of
all branches that correspond to the specified delphes class. Now we can
instead select the different branches by their name, which is also
consistent with how the other configuration parameters work.
- Make delphes output configuration more consistent, by using branch names also for the generated particle collections.

[delphes] Use the branch name instead of the delphes class for GenParticle

---

plugins/delphes/DelphesEDM4HepConverter.cc

Avoid running into a double free, because the EventStore::clearCollections that might be called outside will free the objects wo which we still hold pointers and would free again when we deconstruct the objects that we hold int he maps.
- Fix double free in Delphes EDM4Hep converter that lead to spurious segmentation violations (#89)
Fixes #89

Clear internal maps before the referenced objects are clered by the EventStore

---

init.sh

The CI will override the version with environment variables, but the default version is outdated. Bumping this to the lcg version which contains podio v00-12
- update lcg release used in init script to 97a

Update lcg release used in init script

---

.travis.yml

After #94 the `BUILD_DELPHESEDM4HEP` option is no longer available and can be removed from the travis setup.

Remove last remnants of delphes plugin from travis CI

---

.gitlab-ci.yml
.travis.yml
CMakeLists.txt
README.md
doc/Doxyfile.in
doc/edm4hep_diagram.svg

- Use gitlab CI to deploy doxygen site to eos
This repo is now mirrored to https://gitlab.cern.ch/key4hep/edm4hep (private repo), where it should be able to take advantage of the gitlab infrastructure to deploy doxygen to eos.

Set up Gitlab to deploy doxygen code reference to website

---

.github/workflows/key4hep.yml
.github/workflows/linux.yml
.github/workflows/linux_with_podio.yml
README.md
test/edm4hep_tricktrack.cc

- Add github actions CI workflows
- Fix issue with CI builds that build podio on the fly
Should we keep the travis CI workflows for now and remove them later, or should we migrate to github actions fully in this PR?
The linking problems that the "on-the-fly podio build" has, can easily be fixed by removing the unnecessary includes in the tricktrack test (`#include "podio/ROOTReader.h"` would need the `podio::podioRootIO` target to link against).

Add github actions CI workflows 

---

.github/workflows/lcg_linux.yml
.github/workflows/lcg_linux_with_podio.yml
.gitignore
CMakeLists.txt
test/CMakeLists.txt
test/downstream-project-cmake-test/CMakeLists.txt
test/downstream-project-cmake-test/main.cxx
test/utils/CMakeLists.txt
test/utils/test_kinematics.cpp
utils/CMakeLists.txt
utils/include/edm4hep/kinematics.h

- Add first utility functionality for kinematics living in namespace `edm4hep::utils`:
- `edm4hep::utils::p` returns the total momentum for the passed particle
- `edm4hep::utils::pt` and `edm4hep::utils::pT` returns the transverse momentum for the passed particle
- `edm4hep::utils::p4` returns the four momentum of the passed particle, depending on the (optional) second argument it uses the momentum of the passed particle and either
- the mass of the passed particle if the second argument is `edm4hep::utils::UseMass` (**default**)
- the energy of the passed particle if the second argument is `edm4hep::utils::UseEnergy`
- an arbitrary value for either the mass or the energy if the second argument is `edm4hep::utils::SetMass{value}` or `edm4hep::utils::SetEnergy{value}` …

Add first kinematics utilities

---

edm4hep.yaml
test/reco_particle_ref.cc

- Remove the `RecoParticleRef` datatype again because podio supports subset collections natively now (see AIDASoft/podio#197)
Needs AIDASoft/podio#197 to be merged before this can work.

Remove RecoParticleRef datatype

---

edm4hep.yaml

- Adds missing types to run clicReconstruction with EDM4hep input/output
- Adds Vector2f, TrackerHitPlane, MCRecoTrackerHitPlaneAssociation, MCRecoCaloParticleAssociation, MCRecoClusterParticleAssociation, MCRecoTrackParticleAssociation

Extend data model for clicRecontruction

---

doc/edm4hep_diagram.svg

- [doc] update diagram for v0.4
Adds the recently added TrackerHitPlane and Associations to the diagram. I'm omitting some association names to not make it too crowded, and the names follow a pattern anyway. 
Unrelated to this PR, while looking at the new diagram I started to wonder if podio should not just allow templated assocations between all types. I'll create an issue.

[doc] update diagram for v0.4

---

edm4hep.yaml

- Add association between ReconstructedParticle and Vertex

Add association between ReconstructedParticle and Vertex

---

edm4hep.yaml

- Use fixed width integer types throughout the whole datamodel.
See #112 
Needs AIDAsoft/podio#234

Switch to fixed width integers everywhere

---

edm4hep.yaml
test/hepmc/edm4hep_testhepmc.cc
test/utils/test_kinematics.cpp
test/write_events.h

- With AIDASoft/podio#205 the naming of the podio generated classes has changed and the immutable classes are now default, while mutable classes now have a `Mutable` prefix.

Make necessary changes for podio mutable classes

---

CMakeLists.txt

- Update the supported c++ standards in the CMake configuration (17 and 20 at the moment).
podio generated code requires at least c++17.

Update supported c++ standards

---

.github/workflows/lcg_linux_with_podio.yml

- Update the compilers that are used for the `dev` based CI workflows
See also: AIDASoft/podio#265

CI: update compilers for LCG dev builds

---

cmake/EDM4HEPConfig.cmake.in
test/downstream-project-cmake-test/CMakeLists.txt

- Make EDM4hep export its current version properly for usage in downstream CMake packages.
- Make sure downstream package test covers this.
Fixes #155
Example failure of downstream package usage without properly exporting the version: https://github.com/tmadlener/EDM4hep/runs/6831190866?check_suite_focus=true#step:4:1029

Make sure EDM4hep exports its version properly for downstream cmake usage

---

edm4hep.yaml

As discussed several times, the time of the track is needed. For example, ACTS tracking code does. In addition, this time in ```edm4hep::TrackState``` can be used to obtain the time of the tracks at different points
- TrackState: add time related entries to the covarianceMatrix
TODO:

Adding Time in edm4hep::TrackState

---

CMakeLists.txt
cmake/EDM4HEPBuild.cmake

- [[cmake] set EDM4HEP_SET_RPATH ON by default
- [cmake] deduplicate RPATH settings

[cmake] set EDM4HEP_SET_RPATH ON by default; deduplicate RPATH settings

---

cmake/EDM4HEPConfig.cmake.in
cmake/EDM4HEPCreateConfig.cmake
edm4hep/CMakeLists.txt

This installs the original yaml file to CMAKE_INSTALL_DATADIR/edm4hep` for use by data models that [extend EDM4hep](https://github.com/AIDASoft/podio/pull/317). This DATADIR is exposed to downstream packages as EDM4HEP_DATA_DIR, and can be used as follows:
```
find_package(EDM4HEP REQUIRED)
PODIO_GENERATE_DATAMODEL(eicd eic_data.yaml headers sources
UPSTREAM_EDM edm4hep:${EDM4HEP_DATA_DIR}/edm4hep.yaml
OUTPUT_FOLDER ${CMAKE_CURRENT_BINARY_DIR}
)
```
The [Gnu standard targets](https://www.gnu.org/prep/standards/html_node/Directory-Variables.html) indicate that DATADIR is the "directory for installing idiosyncratic read-only architecture-independent data files" and "you should install your data in a subdirectory" (which seems to be suggest as lower case).
- Install …

feat: install edm4hep.yaml to CMAKE_INSTALL_DATADIR/edm4hep

---

test/CMakeLists.txt

- RDF Test: add libedm4hepRDF.so directory to LD_LIBRARY_PATH, fixes #167

RDF Test: add edm4hepRDF dir to LD_LIBRARY_PATH

---

test/downstream-project-cmake-test/CMakeLists.txt
test/downstream-project-cmake-test/edm4dis.yaml
test/downstream-project-cmake-test/main.cxx

This adds a very light-weight EDM4DIS data model which combines a new data type with EDM4hep data types.
- test and example for data model derived from EDM4hep
Needs #164 and AIDASoft/podio#317

EDM4DIS derived datamodel

---

test/utils/CMakeLists.txt
test/utils/test_kinematics.py
utils/include/edm4hep/utils/kinematics.h

- Fix the `kinematics.h` header only utility file such that it also works when used via PyROOT.
For more details see:
- https://root-forum.cern.ch/t/calling-a-tag-dispatched-function-from-pyroot-does-not-work-with-a-default-tag-argument/51156/4
- wlav/cppyy#78

Make sure that the kinematics.h also works for python

---

edm4hep.yaml
test/utils/CMakeLists.txt
test/utils/test_vector_utils.cpp
utils/include/edm4hep/utils/vector_utils.h
utils/include/edm4hep/utils/vector_utils_legacy.h

As discussed in https://github.com/key4hep/EDM4hep/issues/144, these are some utility classes on vectors to ensure common operations are available. The utils with concepts are more maintainable, but a legacy version is attached too.
Credit to @sly2j
- Add utilities to work with `Vector` component classes including
- (`constexpr`) `operator` overloads for basic arithmetic with vectors
- utility functionality that is commonly used with vectors
- concepts to work with in generic vector related code.
- Include `edm4hep/utils/vector_utils.h` and work with functionality in `edm4hep::utils` namespace
- This include will automatically use the concept powered version if supported by the compiler and fall back to a legacy implementation if not.

Utilities for vector components

---

CMakeLists.txt
README.md

- Bump the minimum cmake version to 3.16. Fixes #166 
- Update minimally required versions of podio and ROOT in README
@andresailer @vvolkl or should we rather go for 3.12 (i.e. the same as podio and dd4hep at the moment)?

Bump minimum CMake version to 3.16

---

doc/Doxyfile.in

- Use agreed upon spelling of lower case "hep" on doxygen ref page header.

Correct spelling of EDM4hep on doxygen ref page

---

CMakeLists.txt

- Make the minimum nlohmann json version 3.10.5, as other patch releases of the 3.10 series, seem to not compile. Fixes #181 

Require a version of nlohmann_json that actually works

---

README.md
edm4hep.yaml
test/read_events.h
test/write_events.h

- Extend for drift chamber and TPC study
- The extended EDMs are tested within CEPCSW, and it works well
- The extended edm4hep::TrackerPulse and edm4hep::TrackerData are similar to what they are in ILC TPC

extend for drift chamber and TPC

---

tools/include/edm4hep2json.hxx

The header file uses it, but it's not included explicitly (and actually
fails to compile locally for me because of this).
- Added string stream include in `edm4hep2json.hxx`

Include sstream header explicitly

---

edm4hep.yaml
test/downstream-project-cmake-test/edm4dis.yaml

- Add `schema_version` to YAML definition now that podio has limited support (see AIDASoft/podio#341)

Add schema_version to YAML definition

---

edm4hep.yaml

- Add missing units to the comments
@wenxingfang and anyone else, any opinion on the units of `charge` for `RawTimeSeries`? I put fC since that is what's there for other charges with units in EDM4hep.
Fix #5

Add missing units to the comments

---

edm4hep/CMakeLists.txt

- Remove root version check inside CMakeLists.txt
since we require much newer than 6 to build, also in the spack recipe

Remove root version check inside CMakeLists.txt

---

utils/README.md
utils/graph-conf.yaml

- Add a configuration file for the new podio visualization tool
To reproduce the last diagram shown in https://github.com/AIDASoft/podio/pull/377 (i.e. with clustering the data types into categories) it is necessary to have a configuration file that defines which groups exists. While it can be in either place I believe it should be here so changes in the data types such as renames are more likely to be applied also to this configuration file.
As a reminder, to get the diagram run (once it's merged and installed) `python path_to_podio/tools/podio-vis path_to_EDM4hep/edm4hep.yaml --graph-conf path_to_EDM4hep/utils/graph-conf.yaml`
We can also agree on which Associations to remove to make the plot nicer which can be removed by adding
``` yaml
Filter:
- …
```

Add a configuration file for the podio visualization tool

---

edm4hep.yaml
test/utils/CMakeLists.txt

- Changed the name of one VectorMember of edm4hep::track from subDetectorHitNumbers to subdetectorHitNumbers to be consistent with other spellings of the word subdetector in the yaml file and in LCIO.

Change in edm4hep.yaml for consistent naming

---

README.md

- Add brief documentation of the `edm4hep2json` tool with minimal documentation of the output JSON schema.

Add brief documentation for the edm4hep2json tool

---

.pre-commit-config.yaml
README.md
edm4hep.yaml
scripts/updateReadmeLinks.py

- Add a script to automatically update the README.md links

Add a script to automatically update the README.md links

---

cmake/EDM4HEPUninstall.cmake
cmake/EDM4HEP_uninstall.cmake.in

- Rename `CMAKE_BINARY_DIR` to `PROJECT_BINARY_DIR`
This is the correct name that should have been in https://github.com/key4hep/EDM4hep/pull/213

Rename `CMAKE_BINARY_DIR` to `PROJECT_BINARY_DIR`

---

edm4hep/CMakeLists.txt

-  Make cmake aliases global to allow the aliases to be seen by other subdirectories at configure time
-  Change cmake aliases used within EDM4hep to `EDM4HEP::` instead of `edm4hep::` since the namespace for external use is `EDM4HEP`, for consistency

Make aliases global

---

.github/workflows/lcg_linux_with_podio.yml
test/utils/CMakeLists.txt

- CI: use same lcg stacks as podio
- Test: update to Catch2 3.4.0, same as in podio, and c++20 compatible

CI: use same lcg stacks as podio

---

test/utils/CMakeLists.txt

- Add `SKIP_CATCH_DISCOVERY` option to turn of `catch_discover_tests` which may not run in the right environment in older cmake versions.
See https://github.com/AIDASoft/podio/pull/425 for similar changes in podio.

Skip catch test discovery if environment requires it

---

edm4hep.yaml

The `schema_version` is required in the model dict at top level, not inside the `options` dict. See https://github.com/AIDASoft/podio/blob/48a4bf6702c081288853a642749459ac5e42d6d4/python/podio/podio_config_reader.py#L425-L432
Alternatively, podio can be told to look in `options`... In any case, without this, we get a warning (podio https://github.com/AIDASoft/podio/commit/5d5c99ccd2d7667db2f3a60a47ded246d0d9dfcc, EDM4hep@ https://github.com/key4hep/EDM4hep/commit/cb92d6ca9501ee91f27b07bbc577bcca095047c6)
```
-- Creating 'edm4hep' datamodel
/home/wdconinc/git/podio/install/python/podio_class_generator.py:97: FutureWarning: Please provide a schema_version entry. It will become mandatory. Setting it to 1 as default
```
<details><summary>cmake configuration</summary>
<pre>
$ cmake -Bbuild -S. …

fix: schema_version is required at top level

---

test/utils/CMakeLists.txt

- Rename the cmake executable or target `unittests` to `unittests_edm4hep`, to avoid possible collisions since the `unittests` name is relatively common
I don't mind the name, it just has to be a different one from `unittests`. Similar to https://github.com/AIDASoft/podio/pull/481

Rename unittests to unittests_edm4hep

---

test/CMakeLists.txt
test/tools/CMakeLists.txt
test/tools/test_all_collections.py
tools/include/edm4hep2json.hxx
tools/src/edm4hep2json.cxx

- edm4hep2json now converts all EDM4hep collections, associations and Podio user data
- added ROOT legacy support for edm4hep2json

edm4hep2json: All EDM4hep collections + ROOT legacy reader

---

include/edm4hep/Constants.h

To not have this string literal in so many locations
- Add a constant for the default expected EventHeader name to be used by the converters and PodioInput

Add EventHeader constant

---

include/edm4hep/Constants.h

- Change EventHeader to EventHeaderName; we already have an EventHeaderCollection and its elements are called EventHeader (`edm4hep::EventHeader` more precisely)
Building can work because there is `edm4hep::EventHeader` and the constant is not namespaced but it's going to break at some point, at the very least you can't do things like `using edm4hep::EventHeader`.

Change EventHeader to EventHeaderName

---

.github/workflows/lcg_linux_with_podio.yml
.github/workflows/pre-commit.yml
CMakeLists.txt
edm4hep/CMakeLists.txt

- Use `FILE_SET` to install the headers in the top folder together with the library. This also adds them in the `BUILD_INTERFACE`, something that a simple `INSTALL` doesn't do.
- Bump the CMake version of the LCG stacks
- Simplify finding ROOT, don't do environment variable manipulation in CMake
`FILE_SET` requires CMake 2.23 so the version of the LCG stacks has to be bumped. I discovered that it also has the nice property that it complains if any of the sources that are attached to the library are not installed.

Use `FILE_SET` to install the headers in `/include` together with the edm4hep library

---

README.md
edm4hep.yaml
test/utils/test_vector_utils.cpp
utils/include/edm4hep/utils/vector_utils.h
utils/include/edm4hep/utils/vector_utils_legacy.h

- Added a Vector4f object for use as a general 4vector. Addresses https://github.com/key4hep/EDM4hep/issues/245

feat: add 4 dimensional vector object

---

README.md

- Fixed formatting of components table in readme
After adding the `Vector4f` in  #248  the formatting of 'components' table in readme was broken. The table is supposed to have three columns, while in some row four cells were given causing rendering problems.

Fix formatting in components table

---

doc/Doxyfile.in

- Fixed doxygen excluded files and path stripping
The documentation generated with doxygen included tests and scripts which aren't part of exposed API
Broken file striping illustration with `edm4hep::Vector3f` [docs](https://edm4hep.web.cern.ch/classedm4hep_1_1_vector3f.html):
Was:
```
edm4hep::Vector3f Class Reference
#include </builds/key4hep/edm4hep/edm4hep/edm4hep/Vector3f.h>
.
.
.
The documentation for this class was generated from the following file:
- edm4hep/edm4hep/Vector3f.h
```
fixed:
```
edm4hep::Vector3f Class Reference
#include <edm4hep/Vector3f.h>
.
.
.
The documentation for this class was generated from the following file:
- edm4hep/Vector3f.h
```

Fixed doxygen excluded files and path stripping

---

README.md
edm4hep.yaml
test/utils/test_kinematics.py

- Switch the `momentum` and `momentumAtEndpoint` of the `MCParticle` from `Vector3f` to `Vector3d`. 
- Add a (deprecated from the beginning) constructor from `Vector3f` to `Vector3d` to ease the transition.
As (partially) discussed in #208 
This breaks building (at least the following):

Make MCParticle momenta use doubles instead of floats

---

test/hepmc/edm4hep_testhepmc.cc
test/read_events.cc
test/write_events.cc
tools/src/edm4hep2json.cxx

- Change ROOTFrame{Writer,Reader} to ROOT{Writer,Reader} following https://github.com/AIDASoft/podio/pull/549
When the #ifs are removed we should specify a requirement of podio 0.99 or greater

Change ROOTFrame{Writer,Reader} to ROOT{Writer,Reader}

---

README.md
edm4hep.yaml
test/utils/test_kinematics.py

Reverts key4hep/EDM4hep#237
- Revert making MCParticle momenta double precision, since this breaks without schema evolution. (Reverts key4hep/EDM4hep#237)
- All particle momenta are effectively zeroed out at the moment.
@wdconinc in case you have picked up `edm4hep@0.10.4` already via spack you will most likely run into issues with that.
**We will bring these changes back in the breaking set of things for v1.0.**
Fixes https://github.com/key4hep/k4MarlinWrapper/issues/170

Revert "Make MCParticle momenta use doubles instead of floats"

---

test/downstream-project-cmake-test/edm4dis.yaml

- Put the `schema_version` to the correct level for the downstream usage tests to keep it working after [podio#556)(https://github.com/AIDASoft/podio/pull/556)

Put the schema_version to the correct level

---

README.md
edm4hep.yaml

- Rename `MCParticle` relations to `particle` in `SimTrackerHit` and `SimPrimaryIonizationCluster` to avoid clashes with the `MCParticle` typename.
- Add `getMCParticle` and `setMCParticle` via `ExtraCode` to keep everything working.
- **This will break the reading of existing files via podio utilities**
Fixes #247

Rename MCParticle relations to particle to avoid clashes with type names

---

README.md
edm4hep.yaml
include/edm4hep/Constants.h

- Add a `double weight` `VectorMember` to the `EventHeader` to allow storing multiple weights.
- **This should not break any existing code as we simply add a new member. However, this will break the possibility of reading existing files through podio**.
- Introduce the `edm4hep::EventWeights` constant to have a consistent name for storing / accessing them in file level metadata.
- Fixes #242

Add weights vector to EventHeader and constant for storing them

---

edm4hep.yaml

- Rename EDep to eDep in SimTrackerHit for consistency with other uses of "eDep"
Fixes https://github.com/key4hep/EDM4hep/issues/180
I think EDep to eDep fits better the variable usage that we have instead of eDep to EDep

Rename EDep to eDep in SimTrackerHit

---

edm4hep.yaml
include/edm4hep/Constants.h

- "EDM4hep authors" as `Author` field for all data types. Fixes https://github.com/key4hep/EDM4hep/issues/255
- Remove the confusing reference to collection parameters. Fixes https://github.com/key4hep/EDM4hep/issues/191
- Homogenize the comments (dot at the end or not, space after // or not). 
Let me know if you want me to remove the two commits homogenizing comments.

Homogenize authors and cleanup docstrings

---

README.md
edm4hep.yaml

- Remove the `edm4hep::ObjectID` component. Fixes #259 
- Remove its usage from the `edm4hep::TrackerHit` and `edm4hep::TrackerHitPlane`
- **This is a breaking change both in code and existing files**. Existing usages might switch to use the `podio::ObjectID` to have effectively the same functionality.

Remove the edm4hep::ObjectID from the components

---

test/CMakeLists.txt
test/test_rdf.py

- Remove any path containing /fccanalyses/ for one test to prevent ROOT from loading FCCAnalyses dictionaries
See this comment: https://github.com/key4hep/EDM4hep/pull/252#issuecomment-1959960236
Tested on top of https://github.com/key4hep/EDM4hep/pull/252, the test runs fine now

Remove any path containing /fccanalyses/ for one test

---

edm4hep.yaml

- Use the units explictly in the yaml file to make them appear nicer in the generated docstrings.

Use the units outside of the comments for nicer docstrings

---

README.md
edm4hep.yaml
tools/include/edm4hep2json.hxx
utils/src/dataframe.cc

- Make the `edm4hep::TrackerHit` an `interface` type and use that in the `edm4hep::Track`.
- Rename the current `edm4hep::TrackerHit` to `edm4hep::TrackerHit3D`
- **This is a breaking change. However, we currently do not plan to implement schema evolution for this**
Breaking changes downstream:
This is one of a few rather breaking changes that we plan to do in the near future towards an EDM4hep version 1.0.
Fixes #218

Use interface types for TrackerHit

---

README.md
edm4hep.yaml

- Add `operator!=` to `VectorXY` classes to keep symmetry with updated podio generated code.
Seems to be necessary to fix podio nightlies which break: https://github.com/AIDASoft/podio/actions/runs/8030346379/job/21937625653#step:6:962

Add operator!= to Vector components

---

README.md
edm4hep.yaml

- added static asserting vector components' member ordering and padding
The `operator[]` of generated vector classes assumes no padding and member ordering same as in the source code. These are reasonable assumptions but not required by the standard. The assumptions can be checked at a compile time

added static asserting vector components' member ordering and padding

---

edm4hep.yaml

- Make sure that `operator[]` of the `VectorNx` types return the correct type.
Follow up on #285 where we somehow missed the wrong return types in the review.

Make sure that operator[] return the right types

---

edm4hep/CMakeLists.txt

- Do not try to set the read-only property ALIAS_GLOBAL
See https://cmake.org/cmake/help/latest/prop_tgt/ALIAS_GLOBAL.html#prop_tgt:ALIAS_GLOBAL and https://cmake.org/cmake/help/latest/policy/CMP0160.html. I get a warning with CMake 3.29.

Do not try to set the read-only cmake property ALIAS_GLOBAL

---

python/edm4hep/__init__.py

- Load Constants.h in python, making some names available like `edm4hep::EventHeaderName`

Load Constants.h in python

---

cmake/EDM4HEPConfig.cmake.in
utils/CMakeLists.txt

- Make sure that the `utils` (currently INTERFACE only) target appears as `edm4hepUtils` "on disk" in order to avoid having on overly generic `libutils.so` once it actually becomes a shared library.
This is a small side-effect that can easily be split off from #268

Give the utils target a more discernible output name

---

doc/Doxyfile.in

- Only pass what is strictly necessary as input to doxygen
- Exclude dependencies to avoid generating empty namespaces in the EDM4hep API reference

Improve Doxygen config to only include what is strictly necessary

---

CMakeLists.txt
README.md
edm4hep.yaml
edm4hep/CMakeLists.txt
include/edm4hep/Constants.h
include/edm4hep/detail/CovMatrixCommon.ipp
test/utils/CMakeLists.txt
test/utils/test_covmatrix_utils.cpp
test/utils/test_kinematics.py
utils/include/edm4hep/utils/cov_matrix_utils.h

- Introduce `edm4hep::CovMatrix[2,3,4,6}f` components to represent covariance matrices
- using `std::array<float, N>` under the hood
- Access functionality that works on enums for defining dimensions and some utilities to do the indexing into the underlying storage
- Introduce some `enum class`es for defining dimensions, e.g. `TrackParams` or `Cartesian`
- Use these components instead of the raw `std::array`s in datatypes and other components and tie the interpretation of the values to the approriate dimension `enum class`
Usage example:
```cpp
#include "edm4hep/TrackerHit3D.h"
void foo(const edm4hep::TrackerHit3D& hit) {
const auto covXY  = hit.getCovMatrix(edm4hep::Cartesian::x, edm4hep::Cartesian:y);
}
```
I am not yet sure whether I really like the …

Add dedicated covariance matrix components and use them

---

README.md
edm4hep.yaml

- Remove ParticleID that was deleted in https://github.com/key4hep/EDM4hep/pull/268 and reintroduced in https://github.com/key4hep/EDM4hep/pull/287
probably because originally the branch was based on EDM4hep before https://github.com/key4hep/EDM4hep/pull/268

Remove ParticleID that was deleted and reintroduced in the last PRs

---

test/read_events.h
utils/src/ParticleIDUtils.cc

- Introduce pre-processor checks to transparently switch to the new `std::optional` return values of `podio::Frame::getParameter` (introduced with [AIDASoft/podio#580](https://github.com/AIDASoft/podio/pull/580))

Transparently introduce switch to optional param values

---

doc/edm4hep_diagram.svg

- Update the schema diagram to reflect the `TrackerHit` as interface
- Add `TrackerHit3D` as new type
- Fix all arrow heads to be consistently black

Update the schema diagram to reflect TrackerHit as interface

---

README.md
edm4hep.yaml
edm4hep/CMakeLists.txt
edm4hep/extra_code/CovMatrixCommon.ipp

- Use declarationFile instead of include in CovMatrix to fix generated documentation for covariance matrix components. Fixes [#296](https://github.com/key4hep/EDM4hep/issues/296)
Closes #296 
Declarations added with `#include` were not appearing in a documentation generated with doxygen. New podio direcative 'declarationFile'  (https://github.com/AIDASoft/podio/pull/601)  includes  these declaration during file generation without relaying on pre-processor and make them visible to doxygen
| Old | New |
|-|-|
|![Screenshot_2024-05-01_14-27-21](https://github.com/key4hep/EDM4hep/assets/37295697/16444c50-cc7e-4aa6-b53c-ff7332dfbc6f)|![covmatrix_fix](https://github.com/key4hep/EDM4hep/assets/37295697/debde81e-972b-40ab-b671-14b43c91c64f) |

Use 'declarationFile' instead of  #include in CovMatrix component

---

.gitlab-ci.yml

- Switch to `alma9` image to fix documentation deploys

Switch to alma9 image to fix doc deploys

---

python/CMakeLists.txt

- Make the python bindings install prefix conform to python conventions by default and allow overriding with the `EDM4HEP_PYTHON_INSTALLDIR` cmake variable
- Default prefix is now `<prefix>/lib[64]/pythonX.Y/site-packages` (where `lib` or `lib64` is defined from the platform defaults and `X.Y` is the python major and minor version).
Fixes #220 
See https://github.com/AIDASoft/podio/pull/599 for some discussion on how we arrived at this solution.

Make the python install prefix conform to python conventions

---

include/edm4hep/Constants.h
utils/src/ParticleIDUtils.cc

- Introduce the `edm4hep::labels` namespace to hold the string constants that are used for consistent labeling / naming of collections or parameters.
- Use this opportunity to homogenize the naming and capitalization of the variables but leave string constants unchanged
- Deprecate existing string constants
As triggered by [this discussion](https://github.com/key4hep/EDM4hep/pull/310#discussion_r1636352789)

Introduce a `labels` namespace for the string constants

---

CMakeLists.txt
README.md

Podio only provides the DEPENDS argument of  PODIO_GENERATE_DATAMODEL since https://github.com/AIDASoft/podio/commit/0a5af60c203147de1e7f0081810e0b2fcfc6be5f, i.e. as of tagged version 1.0. 
The use of DEPENDS was added in https://github.com/key4hep/EDM4hep/pull/308 (not in tagged release yet).
- Require podio 1.0

fix: require podio 1.0 for PODIO_GENERATE_DATAMODEL DEPENDS

---

README.md
edm4hep.yaml
test/tools/test_all_collections.py
tools/include/edm4hep2json.hxx

- Remove some of the drift chamber study types that were introduced in [#179](https://github.com/key4hep/EDM4hep/pull/179) again since they need a bit more consideration
- The removed types and components are: `Hypothesis`, `HitLevelData`, `RecIonizationCluster`, `SimPrimaryIonizationCluster`, `TrackerPulse`
- Keep the types and components that are already in use, mainly `TimeSeries`
- Remove the usage of the removed components from `RecDqdx` to make it a purely reconstruction level type
- Fix script that checks that all types are part of the json dumper
See #322, #323 for discussion on how we arrived at this point.
The changes for `RecDqdx` are also present in #311, leading to a likely merge conflict depending on which PR is merged first
We keep the …

Remove some of the drift chamber study types again

---

README.md
edm4hep.yaml
tools/include/edm4hep2json.hxx

- Remove the `MCRecoTrackerHitPlaneAssociation` as it is no longer necessary
Fixes #301 
- Downstream PRs that have to go in simultaneously
- https://github.com/key4hep/k4FWCore/pull/204
- https://github.com/key4hep/k4EDM4hep2LcioConv/pull/73
- https://github.com/key4hep/k4Reco/pull/3

Remove the `MCRecoTrackerHitPlaneAssociation`

---

test/hepmc/edm4hep_testhepmc.cc
test/read_events.cc
test/read_events.h
test/read_events_sio.cc
test/write_events.cc
test/write_events_sio.cc
tools/src/edm4hep2json.cxx
utils/src/ParticleIDUtils.cc

- Remove compatibility with podio versions before 1.0
Since we already bumped this in our CMake config (https://github.com/key4hep/EDM4hep/pull/327), we can also remove this from our code.
Fixes #306

Remove compatibility with podio versions before v1.0

---

README.md
edm4hep.yaml
test/utils/CMakeLists.txt
test/utils/test_bit_utils.cpp
utils/include/edm4hep/utils/bit_utils.h

- Rename the `Vertex` `primary` field to `type` and make it a 32 bit unsigned integer
- Introduce 3 reserved bits and accompanying utility / ExtraCode functionality for checking primary, secondary or tertiary vertex
- Introduce `setBit` and `checkBit` utility functionality and also use that for the `MCParticle` extra code
Fixes #328 
- https://github.com/key4hep/k4EDM4hep2LcioConv/pull/74 (ready for merge)
- https://github.com/HEP-FCC/FCCAnalyses/pull/382 (under review)

Make the Vertex have a proper `type` bitfield instead of a `primary` field

---

README.md
edm4hep.yaml

as discussed in https://github.com/key4hep/EDM4hep/issues/319. 
Changes in other repos:
- https://github.com/key4hep/k4FWCore/pull/202
- https://github.com/key4hep/k4SimDelphes/pull/119
- https://github.com/key4hep/k4EDM4hep2LcioConv/pull/72
- Remove `radiusOfInnermostHit` from tracks

Remove `radiusOfInnermostHit` from tracks

---

python/edm4hep/__init__.py

Should fix https://github.com/key4hep/EDM4hep/issues/338
- Load libraries without the .so suffix to make it work in other OSes

Load libraries without the .so suffix to make it work in other OSes

---

README.md
edm4hep.yaml
utils/CMakeLists.txt
utils/include/edm4hep/utils/TrackUtils.h
utils/src/TrackUtils.cc

- Remove the `dQ/dx` information from the Track
- Add `TrackPIDHandler` to allow for the reverse lookup
- k4EDM4hep2LcioConv (https://github.com/key4hep/k4EDM4hep2LcioConv/pull/69)
- k4SimDelphes (https://github.com/key4hep/k4SimDelphes/pull/121)
- FCCAnalyses (https://github.com/HEP-FCC/FCCAnalyses/pull/387)
- k4RecTracker (https://github.com/key4hep/k4RecTracker/pull/23)

Remove the dQ/dx information from the track

---

doc/VertexRecoParticleRecos.md
edm4hep.yaml

- Make the `Vertex` have relations to the (decay) particles that were used to build it
- Rename the `ReconstructedParticle` relation to a `Vertex` to `decayVertex` (as dicsussed in [#320](https://github.com/key4hep/EDM4hep/issues/320))
Fixes #320 
- k4EDM4hep2LcioConv (https://github.com/key4hep/k4EDM4hep2LcioConv/pull/82)

Overhaul the relations between `Vertex` and `ReconstructedParticle` 

---

.github/workflows/lcg_linux_with_podio.yml

- Update LCG workflow to use LCG_106 instead of LCG_104

Update LCG workflow to use LCG_106 instead of LCG_104

---

.github/workflows/lcg_linux_with_podio.yml

- CI: Make sure to use the python bindings of podio that we build in CI

CI: Make sure to use the python bindings of podio that we build

---

README.md
edm4hep.yaml

currently it's possible to set only the first N elements of the matrix. I think typically this will be mostly a mistake rather than intentionally filling only the first N.
Also static_cast to float, because with older GCC and Clang this is fine, newer GCC throws a warning and newer Clang a compilation error if it's a double. It's already in the name that it's a float in case it's coming from a double (and narrowing happens).
- Covariance matrices: Check for the size of the input for one of the constructors
- `static_cast` the inputs to `float`

Check for the size of the input for one of the constructors of the covariance matrices

---

edm4hep.yaml

- Bump the schema version of EDM4hep to 2 to have a way to differentiate between *before pre-release* and afterwards

Bump the schema version to 2

---

include/edm4hep/MCRecoCaloAssociationCollection.h
include/edm4hep/MCRecoCaloParticleAssociationCollection.h
include/edm4hep/MCRecoClusterParticleAssociationCollection.h
include/edm4hep/MCRecoParticleAssociationCollection.h
include/edm4hep/MCRecoTrackParticleAssociationCollection.h
include/edm4hep/MCRecoTrackerAssociationCollection.h
include/edm4hep/RecoParticleVertexAssociation.h

- Include the user handle types in the `Collection.h` legacy header files such that they can truly be used transparently.

Make sure association legacy headers are truly transparent

---

tools/CMakeLists.txt
tools/include/edm4hep2json.hxx
tools/src/edm4hep2json.cxx

since legacy files were done with incompatible versions of EDM4hep.
- Drop support for the ROOTLegacyReader when converting to JSON

Drop support for the ROOTLegacyReader when converting to JSON

---

scripts/createEDM4hepFile.py

- Fixed typos in member assignment in `createEDM4hep.py`
Fixed the typos in script creating example edm4hep file.
Due to the typos a new member was created instead of updating a value of an existing one., hence incorrect values were written to the output. Originally reported on  #353.
Since earlier there were some similar issues reported (#355) I checked if there are any more typos by setting a pythonizations that forbids dynamically creating new members:
```python
import cppyy
def freeze_class(klass, name):
def freeze_setattr(self, attr, val):
if not attr in type(self).__dict__:
raise AttributeError(attr)
old_setattr(self,attr,val)
old_setattr = klass.__setattr__ 
klass.__setattr__ = freeze_setattr
cppyy.py.add_pythonization(freeze_class, "edm4hep")
``` …

Fix assignment to non-exisitng members in createEDM4hep.py

---

.github/workflows/lcg_linux_with_podio.yml
.github/workflows/pre-commit.yml

- CI: Update versions of github actions where appropriate
- CI: simplify workflows that build podio and EDM4hep by using cmake commands to invoke the build tool
- CI: Enable more features from podio for building EDM4hep on top of
- Also fix a buggy printout that states the commit of podio that was used for building

CI: Rework workflows to make them a bit easier to maintain

---

CMakeLists.txt
cmake/EDM4HEPBuild.cmake
include/edm4hep/GeneratorToolInfo.h

Several settings for Key4hep packages have been being set manually in CMakeLists.txt and they differ between different packages. A new file `Key4hepConfig.cmake` with some common settings was created (https://github.com/key4hep/key4hep-dev-utils/pull/5) and pushed to several repositories and these are the cmake changes needed to use them. 
The file `Key4hepConfig.cmake` is already in the repositories, so it doesn't need to be added. It was pushed but is not being used anywhere.
- Use the Key4hepConfig flag to set the standard, compiler flags and rpath magic.
- For EDM4hep, the standard keeps being C++20 and the rpath is set as it was before. For the compiler flags `-Wshadow` is added on top of the existing ones.

Use the Key4hepConfig flag to set the standard, compiler flags and rpath magic.

---

edm4hep/CMakeLists.txt

- Inject the EDM4hep version into the metadata that are stored by podio
Technically this also requires a bump in the minimal podio version, but we need a podio tag first for that.

Inject the EDM4hep version into the metadata that are stored by podio

---

python/edm4hep/__init__.py
test/CMakeLists.txt
test/test_module.py

- Added missing attributes for python package
The package attributes from the import system were missing since the `edm4hep` is rebound to the `edm4hep` submodule created with ROOT/cppyy. Similarly `__version__` was set in the `__init__.py` but then lost
Having missing attributes shouldn't be a problem as we didn't experience it yet. But I think there was an intention to have `edm4hep.__version__` available
Import system [docs](https://docs.python.org/3/reference/import.html#import-related-module-attributes)

Add missing attributes for python package

---

test/CMakeLists.txt

Introduced in https://github.com/key4hep/EDM4hep/pull/361, `CMAKE_BINARY_DIR` won't work if EDM4hep is built from another project.
- Use PROJECT_BINARY_DIR instead of CMAKE_BINARY_DIR to always locate the test files

Use PROJECT_BINARY_DIR instead of CMAKE_BINARY_DIR to always locate the test files

---

python/edm4hep/__init__.py
test/test_EDM4hepFile.py

- Added loading pythonizations from podio
Load podio pythonizations (AIDASoft/podio#570) on `import edm4hep`

add loading pythonizations from podio

---

test/CMakeLists.txt
test/conftest.py
test/test_EDM4hepFile.py

- Skip the check for the full file in case the RNTuple has not been produce (e.g. if podio hasn't been built with RNTuple support)
This is a slightly hackish solution that leverages pytests capabilities to skip tests rather than failing them. Unfortunately it returns a non-zero exit code in that case, so we need the `SKIP_REGULAR_EXPRESSION` (which we can now make a bit more narrow). This works around the same issue as https://github.com/AIDASoft/podio/pull/677 but entirely within EDM4hep.
I tried first with cmake features, but neither [`REQUIRED_FILES`](https://cmake.org/cmake/help/latest/prop_test/REQUIRED_FILES.html) nor [`FIXTURES_REQUIRED`](https://cmake.org/cmake/help/latest/prop_test/FIXTURES_REQUIRED.html#prop_test:FIXTURES_REQUIRED) can be made …

Skip the full file check if the rntuple file has not been produced

---

test/hepmc/edm4hep_testhepmc.cc

- Remove unused variable in edm4hep_testhepmc.cc

Remove unused variable in edm4hep_testhepmc.cc

---

.github/workflows/pre-commit.yml
.pre-commit-config.yaml
.ruff.toml
CMakeLists.txt
cmake/pythonFormat.cmake
python/edm4hep/__init__.py
scripts/createEDM4hepFile.py
scripts/updateReadmeLinks.py
test/conftest.py
test/test_EDM4hepFile.py
test/test_rdf.py
test/tools/test_all_collections.py
test/utils/test_kinematics.py

- Added ruff pre-commit hook for formatting and linting python files
- Reformatted and fixed warnings in python files
- Added cmake targets `ruff` and `ruff-format` to lint and format python code
Linting and formatting done with [ruff](https://docs.astral.sh/ruff/) which should be compatible with black, flake8 and pylint while having a single configuration file. ruff is already in the stack
CI added as local hook
Selected [rules](https://docs.astral.sh/ruff/rules/) `["F", "E", "W", "PLE", "PLW", "PLC"]` from flake8 (pyflakes "F", pycodestyle errors "E" and warnings "W") and pylint (errors "PLE", warnings "PLW" and conventions "PLC")
I'd also consider adding some of the `D1` checks for docstrings but there seems to be only a few docstrings now …

add formatting and linting python in pre-commit

---

utils/include/edm4hep/utils/vector_utils.h

- Remove redundant `inline` from templated utility functions.

Remove redundant inline

---

CMakeLists.txt
cmake/EDM4HEPConfig.cmake.in
edm4hep/CMakeLists.txt
tools/CMakeLists.txt

- Add an `EDM4HEP_WITH_JSON` cmake option (default `ON`) to be explicit about whether we want to build EDM4hep with JSON support or not.
- Properly propagate this to downstream packages.
- If set to `OFF` the `edm4hep2json` executable will not be built.

Find nlohmann_json downstream if EDM4hep has support

---

test/backwards_compat/CMakeLists.txt

- Make sure to only run backwards compatibility tests if we have a suitable version of ROOT to still read the RC2 RNTuples stored in the files.
Necessary to make the full CI suite pass again for https://github.com/AIDASoft/podio/pull/702

Make sure to only run tests with compatible root versions

---

edm4hep/CMakeLists.txt

- Install oldSchemas library and dictionary
The oldSchemas library added in #373 wasn't added for installation, while being expected to be installed by python bindings:
```txt
File "/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2024-12-19/x86_64-almalinux9-gcc14.2.0-opt/edm4hep/d651cd6792eb29808c18f742280508735f040269_develop-45e6w4/lib/python3.11/site-packages/edm4hep/__init__.py", line 30, in <module>
raise RuntimeError("Failed to load edm4hep legacy schemas library")
RuntimeError: Failed to load edm4hep legacy schemas library
```

install old schemas libraries

---

CMakeLists.txt

- Bump the minimal podio version to 1.2, since the `links` category in the YAML file was only introduced there.
Another follow up from #373

Bump minimal podio version

---

utils/include/edm4hep/utils/ParticleIDUtils.h

- Make the PIDHandler class non-copyable
Sounds like a bad idea to copy all these maps, vector of strings, strings...

Make the PIDHandler class non-copyable

---

doc/Doxyfile.in
doc/edm4hep_footer.html
doc/edm4hep_header.html
doc/edm4hep_stylesheet.css

- Updated doxygen files to the version 1.11 so a dark mode renders properly
The config for oxygen was for an older version (1.8) that we had in stack (1.11). One change that I care about is the dark mode which with 1.8 is partially not readable (top level header is black on black background, code snippets from markdown are light grey on white). For light mode the changes seem to be minimal.
These are both "dark mode"
| 1.8 | 1.11 |
|-|-|
| ![image](https://github.com/user-attachments/assets/40739e84-265a-43e9-bd13-abb8e2e3a3cb) | ![image](https://github.com/user-attachments/assets/fce80168-ee04-42c4-ac84-d2f5620d6295) |
| ![image](https://github.com/user-attachments/assets/4a31f7a3-47f5-4588-921e-e93a9fee0590) | …

update doxygen files to 1.11

---

edm4hep/CMakeLists.txt

- Make sure to also install the `rootmap` and `rdict` files for the old schemas library
Follow up on #373 and #391, so that we now hopefully have everything installed that is necessary.

Install rootmap for old schema dictionaries

---

README.md

- Fix component table in readme so it renders correctly
The first row of component table had an extra empty column (leftover from removing `Vector2i` #389). It was rendering fine on github but broken in doxygen markdown renderer

fix component table in readme

---

doc/PIDHandler.md
test/utils/test_PIDHandler.cpp
utils/include/edm4hep/utils/ParticleIDUtils.h
utils/src/ParticleIDUtils.cc

- Add proper docstrings to all ParticleID related utilities (`edm4hep::utils::ParticleIDMeta` and `edm4hep::utils::PIDHandler`).
- Add a `addMetaInfos` convenience overload to the `PIDHandler` to allow passing in several meta objects at once.

Add documentation and a convenience overload to the ParticleID utilities

---

README.md
edm4hep.yaml

I propose here to use YAML's native support for multiline strings to make the extra code and declarations etc more maintainable. It allows implicitly taking newlines from the string, which allows skipping putting them in explicitly.
- Refactored YAML to use multiline strings

Use YAML multiline strings for extra code

---

utils/include/edm4hep/utils/cov_matrix_utils.h

- Use `std::swap` (available now that we compile with C++20) and add a default
case for the switch statement in the covariance matrix utils

Use std::swap and add a default case for the switch statement

---

doc/DoxygenLayout.xml

- Added a tab with standalone documentation pages in doxygen docs
Adding tabs:
-`Release notes`
-`Selected topics` - I'm not entirely convinced by this name.
I didn't figure out if there is a way to use more readable references to the files

show standalone documentation pages in doxygen docs

---

.github/workflows/pre-commit.yml
include/edm4hep/GeneratorToolInfo.h

- Switch pre-commit workflow to run on Key4hep nightlies to have a recent enough version of `clang-format`.

Run pre-commit on Key4hep to have a recent enough clang-format

---

edm4hep.yaml

- Add missing units for covariances, particle charge and other members
There are some cases where a unit was missing, mostly for covariances. I also suggest to add that particle charge is measured in the units the elementary charge

add missing units in datamodel yaml file

---

edm4hep/schema_evolution/src/OldLinkEvolution.cc

- Replace `podio::detail::linkCollTypeName` with  link collection `typeName` introduced in AIDASoft/podio#748
Replace `podio::detail::linkCollTypeName` with  link collection `typeName` introduced in AIDASoft/podio#748

use link collection `typeName`

---

python/edm4hep/__init__.py

- Remove intermediate variables and make loading libraries and files consistent in `__init__.py`
< 0 is bad (see https://root.cern.ch/doc/master/classTSystem.html#a6ff4c4c6cd8a75a199a30dd94359f205)  but 1 is returned when the library has already been loaded, which is not that bad but maybe we should know if that ever happens.

Remove intermediate variables and make loading consistent in `__init__.py`

---

.github/workflows/lcg_linux_with_podio.yml

- Switch to latest actions for CI and enable caching of build artifacts for speeding up workflows

Switch to latest actions and cache build artifacts

---

CMakeLists.txt

- Bump the required version of podio to 1.3. This is needed since ::typeName in link collections are only present in 1.3 and onwards. See https://github.com/key4hep/EDM4hep/issues/415
Closes #415
For versioning, EDM4hep 0.99.1 doesn't build with podio 1.3.

Bump the required version of podio to 1.3.

---

tools/include/edm4hep2json.hxx

- Fix `edm4hep2json` not recognizing generator metadata types
The strings for edm4hep generator metada types hardcoded in edm4hep2json were wrong so those types couldn't be recognized.
For example reading file created with `createEDM4hepFile.py` gives:
```
$ edm4hep2json edm4hep.root 
WARNING: Collection type not recognized!
edm4hep::GeneratorEventParametersCollection
WARNING: Collection type not recognized!
edm4hep::GeneratorPdfInfoCollection
WARNING: Collection type not recognized!
edm4hep::GeneratorEventParametersCollection
WARNING: Collection type not recognized!
edm4hep::GeneratorPdfInfoCollection
WARNING: Collection type not recognized!
edm4hep::GeneratorEventParametersCollection
WARNING: Collection type not recognized! …
```

fix `edm4hep2json` not recognizing generator metadata types
